In [4]:
"Importar la librería numpy y reconocer la versión utilizada"
import numpy as np
print(f"La versión de numpy es la {np.__version__}")

La versión de numpy es la 1.26.4


In [6]:
def introduccion_arrays():
    print("=" * 50)
    print("IMPORTACIÓN Y CREACIÓN DE ARRAYS")
    print("=" * 50)

    #Crear el primer array (vector o arreglo) con NumPy
    arreglo_numerico = [1, 2, 3, 4, 5]
    vector_inicial = np.array(arreglo_numerico)

    print(f"El arreglo_numerico es del tipo = {type(arreglo_numerico)}")
    print(f"El vector_inicial es del tipo = {type(vector_inicial)}")
    print(f"Vector inicial: {vector_inicial}")

    #Crear una matriz
    matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
    print(f"\nTipo de matriz: {type(matriz)}")
    print(f"Matriz:\n{matriz}")

    return vector_inicial, matriz

def operaciones_vectorizadas():
    print("=" * 50)
    print("OPERACIONES VECTORIZADAS")
    print("=" * 50)

    matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(f"Matriz original:\n{matriz}")

    #Multiplicar todos los elementos por 2
    resultado_por2 = matriz * 2
    print(f"\nMatriz multiplicada por 2:\n{resultado_por2}")

    #Otras operaciones vectorizadas
    suma_resultado = matriz + 10
    print(f"\nMatriz + 10:\n{suma_resultado}")

    potencia_resultado = matriz ** 2
    print(f"\nMatriz al cuadrado:\n{potencia_resultado}")

    return resultado_por2, suma_resultado, potencia_resultado

def crear_secuencias():
    print("=" * 50)
    print("CREAR SECUENCIAS EN ARREGLOS Y MATRICES")
    print("=" * 50)

    #Crear secuencia con arange. np.arange(inicio, fin, paso)
    arreglo_secuencial = np.arange(0, 10, 2)
    print(f"Secuencia con arange(0, 10, 2): {arreglo_secuencial}")

    #Crear secuencia con linspace. np.linspace(inicio, fin, cantidad de puntos)
    arreglo_linspace = np.linspace(0, 1, 5)
    print(f"Secuencia con linspace(0, 1, 5): {arreglo_linspace}")

    #Crear secuencia con logspace. np.logspace(inicio, fin, cantidad de puntos), en escala loga
    arreglo_logspace = np.logspace(0, 2, 5)
    print(f"Secuencia con logspace(0, 2, 5): {arreglo_logspace}")

    return arreglo_secuencial, arreglo_linspace, arreglo_logspace

def matrices_especiales():
    print("=" * 50)
    print("CREACIÓN DE MATRICES ESPECIALES")
    print("=" * 50)
    print("Utilidad: procedimientos de prueba, inicialización de redes neuronales,")
    print("generación de datos ficticios")
    print()

    #Matriz de ceros
    matriz_ceros = np.zeros((3, 3))
    print(f"Matriz de ceros (3x3):\n{matriz_ceros}")

    #Matriz de unos
    matriz_unos = np.ones((3, 3))
    print(f"\nMatriz de unos (3x3):\n{matriz_unos}")

    #Matriz identidad
    matriz_identidad = np.eye(3)
    print(f"\nMatriz identidad (3x3):\n{matriz_identidad}")

    #Matriz aleatoria
    np.random.seed(42) #Asegura que la secuencia de números sea reproducible
    matriz_aleatoria = np.random.rand(3,3)
    print(f"\nMatriz aleatoria (3x3):\n{matriz_aleatoria}")

    #Matriz valores específicos
    matriz_llena = np.full((3, 3), 7)
    print(f"\nMatriz llena de 7s (3x3):\n{matriz_llena}")

    return matriz_ceros, matriz_unos, matriz_identidad, matriz_aleatoria, matriz_llena

def seleccion_elementos():
    print("=" * 50)
    print("SELECCIÓN DE ELEMENTOS")
    print("=" * 50)

    #Selección en vector
    vector = np.array([1, 2, 3, 4, 5])
    elemento_seleccion = vector[2]
    print(f"Vector: {vector}")
    print(f"Elemento en índice 2: {elemento_seleccion}")

    #Selección en matriz
    matriz_seleccion = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    elemento_seleccion_matriz = matriz_seleccion[1, 1]
    print(f"\nMatriz:\n{matriz_seleccion}")
    print(f"Elemento en posición [1, 1]: {elemento_seleccion_matriz}")

    #Selección múltiple
    indices = [0, 2, 4]
    elementos_multiples = vector[indices]
    print(f"\nElementos en índices {indices}: {elementos_multiples}")

    #Selección condicional
    elementos_mayores = vector[vector > 3]
    print(f"Elementos mayores a 3: {elementos_mayores}")

    return vector, matriz_seleccion, elementos_multiples

def submatrices_slicing():
    print("=" * 50)
    print("SUBMATRICES POR SLICING")
    print("=" * 50)

    matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(f"Matriz original:\n{matriz}")

    #Extraer submatriz (filas 0-1, columnas 1-2)
    submatriz = matriz[1:2, 1:3]
    print(f"\nSubmatriz [0:2, 1:3]:\n{submatriz}")

    #Extraer toda una columna
    columna = matriz[:,0]
    print(f"\nPrimera columna completa: {columna}")

    #Extraer toda una fila
    fila = matriz[1, :]
    print(f"Segunda fila completa: {fila}")

    #Extraer elementos alternos
    elementos_alternos = matriz[::2, ::2]
    print(f"\nElementos alternos:\n{elementos_alternos}")

    return matriz, submatriz, columna, fila

def funciones_estadisticas():
    print("=" * 50)
    print("FUNCIONES ESTADÍSTICAS CON NUMPY")
    print("=" * 50)

    datos = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    print(f"Datos: {datos}")

    #Calcular estadisticas
    media = np.mean(datos)
    mediana = np.median(datos)
    desviacion = np.std(datos)
    varianza = np.var(datos)
    minimo = np.min(datos)
    maximo = np.max(datos)
    suma = np.sum(datos)

    #Mostrar resultados organizados
    estadisticas = {
        'Media': media,
        'Mediana': mediana,
        'Desviación Estándar': desviacion,
        'Varianza': varianza,
        'Valor Mínimo': minimo,
        'Valor Máximo': maximo,
        'Sumatoria': suma
    }
    print("RESULTADOS ESTADÍSTICOS:")
    print("-" * 30)
    for nombre, valor in estadisticas.items():
        print(f"{nombre:20}: {valor:.4f}")

    # Estadísticas adicionales
    percentil_25 = np.percentile(datos, 25)
    percentil_75 = np.percentile(datos, 75)
    rango = maximo - minimo

    print(f"\nESTADÍSTICAS ADICIONALES:")
    print("-" * 30)
    print(f"{'Percentil 25':20}: {percentil_25:.4f}")
    print(f"{'Percentil 75':20}: {percentil_75:.4f}")
    print(f"{'Rango':20}: {rango:.4f}")

    return datos, estadisticas

def operaciones_matriciales():
    print("=" * 50)
    print("OPERACIONES MATRICIALES AVANZADAS")
    print("=" * 50)

    #Crear matrices de ejemplo
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    print(f"Matriz A:\n{A}")
    print(f"\nMatriz B:\n{B}")

    # Multiplicación de matrices
    producto_matricial = np.dot(A, B)
    print(f"\nProducto matricial (A @ B):\n{producto_matricial}")

    # Transposición
    A_transpuesta = A.T
    print(f"\nTranspuesta de A:\n{A_transpuesta}")

    # Determinante
    det_A = np.linalg.det(A)
    print(f"\nDeterminante de A: {det_A:.4f}")

    # Inversa
    try:
        inv_A = np.linalg.inv(A)
        print(f"\nInversa de A:\n{inv_A}")
    except np.linalg.LinAlgError:
        print("\nLa matriz A no es invertible")

    # Valores y vectores propios
    eigenvalues, eigenvectors = np.linalg.eig(A)
    print(f"\nValores propios de A: {eigenvalues}")
    print(f"Vectores propios de A:\n{eigenvectors}")

    return A, B, producto_matricial, A_transpuesta

def menu_principal():
    """Función principal que muestra el menú de opciones"""
    opciones = {
        '1': ('Introducción a Arrays', introduccion_arrays),
        '2': ('Operaciones Vectorizadas', operaciones_vectorizadas),
        '3': ('Crear Secuencias', crear_secuencias),
        '4': ('Matrices Especiales', matrices_especiales),
        '5': ('Selección de Elementos', seleccion_elementos),
        '6': ('Submatrices por Slicing', submatrices_slicing),
        '7': ('Funciones Estadísticas', funciones_estadisticas),
        '8': ('Operaciones Matriciales Avanzadas', operaciones_matriciales),
        '0': ('Salir', None)
    }

    while True:
        print("\n" + "=" * 60)
        print("         TUTORIAL INTERACTIVO DE NUMPY")
        print("=" * 60)
        print("Seleccione una característica de NumPy para explorar:")
        print("-" * 60)

        for codigo, (descripcion, _) in opciones.items():
            print(f"  {codigo}. {descripcion}")

        print("-" * 60)
        opcion = input("\nIngrese su opción: ").strip()

        if opcion == '0':
            print("\n¡Gracias por usar el tutorial de NumPy!")
            break
        elif opcion in opciones and opcion != '0':
            print("\n")
            try:
                opciones[opcion][1]()
                input("\nPresione Enter para continuar...")
            except Exception as e:
                print(f"Error al ejecutar la función: {e}")
        else:
            print("\n❌ Opción no válida. Por favor, seleccione una opción del menú.")

# Ejecutar el menú principal
menu_principal()


         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  1




IMPORTACIÓN Y CREACIÓN DE ARRAYS
El arreglo_numerico es del tipo = <class 'list'>
El vector_inicial es del tipo = <class 'numpy.ndarray'>
Vector inicial: [1 2 3 4 5]

Tipo de matriz: <class 'numpy.ndarray'>
Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



Presione Enter para continuar... 



         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  2




OPERACIONES VECTORIZADAS
Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz multiplicada por 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matriz + 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Matriz al cuadrado:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]



Presione Enter para continuar... 



         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  8




OPERACIONES MATRICIALES AVANZADAS
Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Producto matricial (A @ B):
[[19 22]
 [43 50]]

Transpuesta de A:
[[1 3]
 [2 4]]

Determinante de A: -2.0000

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Valores propios de A: [-0.37228132  5.37228132]
Vectores propios de A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



Presione Enter para continuar... 



         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  7




FUNCIONES ESTADÍSTICAS CON NUMPY
Datos: [ 1  2  3  4  5  6  7  8  9 10]
RESULTADOS ESTADÍSTICOS:
------------------------------
Media               : 5.5000
Mediana             : 5.5000
Desviación Estándar : 2.8723
Varianza            : 8.2500
Valor Mínimo        : 1.0000
Valor Máximo        : 10.0000
Sumatoria           : 55.0000

ESTADÍSTICAS ADICIONALES:
------------------------------
Percentil 25        : 3.2500
Percentil 75        : 7.7500
Rango               : 9.0000



Presione Enter para continuar... 0



         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  11



❌ Opción no válida. Por favor, seleccione una opción del menú.

         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------



Ingrese su opción:  0



¡Gracias por usar el tutorial de NumPy!
