**Paso 1:** Importar librería NumPy

In [1]:
import numpy as np
print(F"NumPy importado exitosamente. Versión = {np.__version__}")

NumPy importado exitosamente. Versión = 1.26.4


**Paso 2:** Crear una matriz de 3x3 con números enteros del 1-9

In [2]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(F"Matriz original 'a' =\n{a}")
print(F"Dimensión de la matriz 'a' = {a.shape}")
print(F"Tipo de datos: {a.dtype}")

Matriz original 'a' =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensión de la matriz 'a' = (3, 3)
Tipo de datos: int32


**Paso 3:** Sumar 10 a cada elemento de la matriz

In [3]:
a_suma = a + 10
print("--Suma a la matriz original de 10 por cada elemento--")
print(a_suma)

--Suma a la matriz original de 10 por cada elemento--
[[11 12 13]
 [14 15 16]
 [17 18 19]]


**Paso 4:** Multiplicar por 2 cada elemento de la matriz

In [4]:
a_multiplicada = a * 2
print("--Multiplicación a la matriz original por 2 en cada elemento--")
print(a_multiplicada)

--Multiplicación a la matriz original por 2 en cada elemento--
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**Paso 5:** Extracción de elementos mayores a 5 con selección condicional

In [6]:
a_condicional = a > 5
print("--La condición es que los elementos sean mayores a 5--")
print(a_condicional)
print("--Elementos que son mayores a 5--")
elementos_mayores = a[a_condicional]
print(elementos_mayores)

--La condición es que los elementos sean mayores a 5--
[[False False False]
 [False False  True]
 [ True  True  True]]
--Elementos que son mayores a 5--
[6 7 8 9]


**Paso 6:** Asigna la matriz 'matriz_original' nueva matriz 'referencia' y modifica un valor de 'referencia' para ver el comportamiento

In [10]:
print("DEMOSTRACIÓN: REFERENCIAS vs COPIAS EN NUMPY")
print("=" * 50)

# ============================================================================
# PARTE 1: CREACIÓN DE MATRIZ ORIGINAL
# ============================================================================
print("\nPARTE 1: Creación de matriz original")
print("-" * 50)

# Crear matriz original
matriz_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

print("Matriz original creada:")
print(f"Contenido:\n{matriz_original}")
print(f"ID en memoria: {id(matriz_original)}")

# ============================================================================
# PARTE 2: DEMOSTRACIÓN DE REFERENCIA (¡PELIGRO!)
# ============================================================================
print("\nPARTE 2: Asignación por referencia")
print("-" * 50)

# IMPORTANTE: Esto NO crea una copia, sino una referencia
# 'referencia' apunta al mismo objeto en memoria que 'matriz_original'
referencia = matriz_original

print("Después de hacer: referencia = matriz_original")
print(f"ID de matriz_original: {id(matriz_original)}")
print(f"ID de referencia: {id(referencia)}")
print(f"¿Son el mismo objeto? {matriz_original is referencia}")  # True
print(f"¿Son iguales en contenido? {np.array_equal(matriz_original, referencia)}")  # True

print("\nContenido de ambas matrices:")
print(f"Matriz original:\n{matriz_original}")
print(f"Referencia:\n{referencia}")

# ============================================================================
# PARTE 3: MODIFICAR REFERENCIA - ¡EFECTO SORPRESA!
# ============================================================================
print("\nPARTE 3: Modificando referencia - ¡Efecto sorpresa!")
print("-" * 50)

# Modificamos un elemento de la referencia
# Como es una referencia al mismo objeto, esto también cambia la matriz original
print("Ejecutando: referencia[1, 1] = 99")
referencia[1, 1] = 99

print("\nRESULTADO INESPERADO:")
print("Matriz original (¡se modificó también!):")
print(f"{matriz_original}")
print("Referencia:")
print(f"{referencia}")

print("\nANÁLISIS:")
print("• 'matriz_original' y 'referencia' son el mismo objeto en memoria")
print("• Modificar 'referencia' también modifica 'matriz_original'")
print("• Esto puede causar errores difíciles de detectar en programas grandes")

DEMOSTRACIÓN: REFERENCIAS vs COPIAS EN NUMPY

PARTE 1: Creación de matriz original
--------------------------------------------------
Matriz original creada:
Contenido:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ID en memoria: 2035343323280

PARTE 2: Asignación por referencia
--------------------------------------------------
Después de hacer: referencia = matriz_original
ID de matriz_original: 2035343323280
ID de referencia: 2035343323280
¿Son el mismo objeto? True
¿Son iguales en contenido? True

Contenido de ambas matrices:
Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Referencia:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

PARTE 3: Modificando referencia - ¡Efecto sorpresa!
--------------------------------------------------
Ejecutando: referencia[1, 1] = 99

RESULTADO INESPERADO:
Matriz original (¡se modificó también!):
[[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]
Referencia:
[[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]

ANÁLISIS:
• 'matriz_original' y 'referencia' son el mismo objeto en memoria
• Modificar 'referencia' también

**Paso 7:** Mismo ejercicio que el Paso 6 pero ahora utilizando la función copy() de NumPy para ver la diferencia de comportamiento

In [11]:
# ============================================================================
# PARTE 1: SOLUCIÓN - USAR COPY() PARA COPIA INDEPENDIENTE
# ============================================================================
print("\nPARTE 1: Solución usando copy()")
print("-" * 50)

# Restaurar matriz original para la siguiente demostración
matriz_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# NumPy tiene una función para crear una copia real
# copy() crea un nuevo objeto independiente en memoria
copia_independiente = matriz_original.copy()

print("Después de hacer: copia_independiente = matriz_original.copy()")
print(f"ID de matriz_original: {id(matriz_original)}")
print(f"ID de copia_independiente: {id(copia_independiente)}")
print(f"¿Son el mismo objeto? {matriz_original is copia_independiente}")  # False
print(f"¿Son iguales en contenido? {np.array_equal(matriz_original, copia_independiente)}")  # True

print("\nContenido inicial:")
print(f"Matriz original:\n{matriz_original}")
print(f"Copia independiente:\n{copia_independiente}")

# ============================================================================
# PARTE 2: MODIFICAR COPIA INDEPENDIENTE
# ============================================================================
print("\nPARTE 2: Modificando copia independiente")
print("-" * 50)

# Modificamos la copia independiente
print("Ejecutando: copia_independiente[1, 1] = 99")
copia_independiente[1, 1] = 99

print("\nRESULTADO ESPERADO:")
print("Matriz original (NO se modificó):")
print(f"{matriz_original}")
print("Copia independiente (solo esta cambió):")
print(f"{copia_independiente}")

print("\nANÁLISIS:")
print("• 'matriz_original' y 'copia_independiente' son objetos diferentes")
print("• Modificar 'copia_independiente' NO afecta a 'matriz_original'")
print("• Esta es la forma segura de trabajar con copias")

# ============================================================================
# PARTE 3: COMPARACIÓN DE MÉTODOS DE COPIA
# ============================================================================
print("\nPARTE 3: Diferentes métodos de copia")
print("-" * 50)

# Crear matriz de prueba
matriz_prueba = np.array([[10, 20], [30, 40]])

# Diferentes formas de crear copias independientes
copia_metodo1 = matriz_prueba.copy()           # Método .copy()
copia_metodo2 = np.array(matriz_prueba)        # Constructor np.array()
copia_metodo3 = np.copy(matriz_prueba)         # Función np.copy()

print("Matriz de prueba:")
print(f"ID: {id(matriz_prueba)}")
print(f"Contenido:\n{matriz_prueba}")

print(f"\nMétodo 1 - .copy():")
print(f"ID: {id(copia_metodo1)}")
print(f"¿Es independiente? {matriz_prueba is not copia_metodo1}")

print(f"\nMétodo 2 - np.array():")
print(f"ID: {id(copia_metodo2)}")
print(f"¿Es independiente? {matriz_prueba is not copia_metodo2}")

print(f"\nMétodo 3 - np.copy():")
print(f"ID: {id(copia_metodo3)}")
print(f"¿Es independiente? {matriz_prueba is not copia_metodo3}")

# ============================================================================
# PARTE 4: PRUEBA FINAL - VERIFICACIÓN DE INDEPENDENCIA
# ============================================================================
print("\nPARTE 4: Prueba final de independencia")
print("-" * 50)

# Modificar matriz original y verificar que las copias no se afecten
print("Modificando matriz_prueba[0, 0] = 999")
matriz_prueba[0, 0] = 999

print("\nResultados después de modificar la matriz original:")
print(f"Matriz original: {matriz_prueba[0, 0]} (cambió)")
print(f"Copia método 1: {copia_metodo1[0, 0]} (no cambió)")
print(f"Copia método 2: {copia_metodo2[0, 0]} (no cambió)")
print(f"Copia método 3: {copia_metodo3[0, 0]} (no cambió)")

# ============================================================================
# RESUMEN Y MEJORES PRÁCTICAS
# ============================================================================
print("\nRESUMEN Y MEJORES PRÁCTICAS")
print("-" * 50)

print("REGLAS FUNDAMENTALES:")
print("1. 'b = a' crea una REFERENCIA al mismo objeto")
print("2. 'c = a.copy()' crea una COPIA INDEPENDIENTE")
print("3. Modificar una referencia afecta al objeto original")
print("4. Modificar una copia NO afecta al objeto original")

print("\nMÉTODOS DE COPIA RECOMENDADOS:")
print("• matriz.copy() - Método más común y directo")
print("• np.copy(matriz) - Función de NumPy")
print("• np.array(matriz) - Constructor (también hace copia)")

print("\nCUÁNDO USAR CADA UNO:")
print("• Usa REFERENCIAS cuando quieras que los cambios se reflejen")
print("• Usa COPIAS cuando necesites modificar sin afectar el original")
print("• En caso de duda, usa .copy() para evitar sorpresas")


PARTE 1: Solución usando copy()
--------------------------------------------------
Después de hacer: copia_independiente = matriz_original.copy()
ID de matriz_original: 2035343324816
ID de copia_independiente: 2035343322224
¿Son el mismo objeto? False
¿Son iguales en contenido? True

Contenido inicial:
Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Copia independiente:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

PARTE 2: Modificando copia independiente
--------------------------------------------------
Ejecutando: copia_independiente[1, 1] = 99

RESULTADO ESPERADO:
Matriz original (NO se modificó):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Copia independiente (solo esta cambió):
[[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]

ANÁLISIS:
• 'matriz_original' y 'copia_independiente' son objetos diferentes
• Modificar 'copia_independiente' NO afecta a 'matriz_original'
• Esta es la forma segura de trabajar con copias

PARTE 3: Diferentes métodos de copia
--------------------------------------------------
Matriz de prueba:
ID: 203