## Generación de datos y redimensionado con NumPy

**Paso 1:** importar librería NumPy

In [2]:
import numpy as np
print("---EJERCICIO: Generación de datos y redimensionado---\n")
print(F"NumPy importado exitosamente. Versión = {np.__version__}")

---EJERCICIO: Generación de datos y redimensionado---

NumPy importado exitosamente. Versión = 1.26.4


**Paso 2:** Crear un arreglo con **np.arange()** y redimensionarlo en una matriz 4x4

In [4]:
x = np.arange(1, 17)
print(F"Arreglo creado y se llama 'x' = {x}")
print(F"Dimensionado original (ARREGLO UNIDIMENSIONAL) = {x.shape}")

x_redimensionado = x.reshape(4, 4)
print(F"Nueva dimensión de la matriz = 4x4")
print(F"Matriz nueva = \n{x_redimensionado}")
print(F"Nuevo dimensionado (MATRIZ 4x4) = {x_redimensionado.shape}")

Arreglo creado y se llama 'x' = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Dimensionado original (ARREGLO UNIDIMENSIONAL) = (16,)
Nueva dimensión de la matriz = 4x4
Matriz nueva = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Nuevo dimensionado (MATRIZ 4x4) = (4, 4)


**Paso 3:** Crear un arreglo de 10 elementos equidistantes entre 0 y 100 usando **np.linspace()**

In [5]:
y = np.linspace(0, 100, 10)
print(F"Arreglo creado y se llama 'y' = \n{y}")
print(F"Dimensionado original = {y.shape}")

Arreglo creado y se llama 'y' = 
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
Dimensionado original = (10,)


**Paso 4**: Crear una matriz aleatoria 3x3 con enteros entre 1 y 20

In [6]:
# Si yo quisiera trabajar con reproducibilidad
z = np.random.randint(1, 21, size=(3, 3))
print(F"Arreglo creado y se llama 'z' = \n{z}")
print(F"Dimensionado original = {z.shape}")

Arreglo creado y se llama 'z' = 
[[ 9  8  8]
 [ 9 13 13]
 [ 3  4 14]]
Dimensionado original = (3, 3)


**Paso 5:** Aplicar funciones matemáticas

In [7]:
print("- Aplicando raíz cuadrada a la matriz 'x_redimensionado'")
x_sqrt = np.sqrt(x_redimensionado)
print(F"Matriz original = \n{x_redimensionado}")
print(F"Raíz cuadrada calculada = \n{x_sqrt}")

- Aplicando raíz cuadrada a la matriz 'x_redimensionado'
Matriz original = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Raíz cuadrada calculada = 
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]


In [8]:
print("- Aplicando logaritmo natural a la matriz 'x_redimensionado'")
x_log = np.log(x_redimensionado)
print(F"Matriz original = \n{x_redimensionado}")
print(F"Logaritmo natural calculado = \n{x_log}")

- Aplicando logaritmo natural a la matriz 'x_redimensionado'
Matriz original = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Logaritmo natural calculado = 
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]


**Paso 6:** Diferencias entre aplicar funciones en arreglos de enteros vs flotantes

In [9]:
print("- Creación de arreglos para el ejemplo")
arr_int = np.array([1,4,9,16], dtype=int)
arr_float = np.array([1.0,4.0,9.0,16.0], dtype=float)

print(F"Arreglo de enteros = {arr_int} (dtype = {arr_int.dtype})")
print(F"Arreglo de flotantes = {arr_float} (dtype = {arr_float.dtype})")

print("\n- Aplicando el cálculo de la raíz cuadrada")
sqrt_int = np.sqrt(arr_int)
sqrt_float = np.sqrt(arr_float)
print(F"Aplicando raíz cuadrada al arreglo de enteros: {sqrt_int} (dtype = {sqrt_int.dtype})")
print(F"Aplicando raíz cuadrada al arreglo de flotantes: {sqrt_float} (dtype = {sqrt_float.dtype})")

print("\n- Aplicando el cálculo del logaritmo natural")
log_int = np.log(arr_int)
log_float = np.log(arr_float)
print(F"Aplicando logaritmo al arreglo de enteros: {log_int} (dtype = {log_int.dtype})")
print(F"Aplicando logaritmo al arreglo de flotantes: {log_float} (dtype = {log_float.dtype})")

- Creación de arreglos para el ejemplo
Arreglo de enteros = [ 1  4  9 16] (dtype = int32)
Arreglo de flotantes = [ 1.  4.  9. 16.] (dtype = float64)

- Aplicando el cálculo de la raíz cuadrada
Aplicando raíz cuadrada al arreglo de enteros: [1. 2. 3. 4.] (dtype = float64)
Aplicando raíz cuadrada al arreglo de flotantes: [1. 2. 3. 4.] (dtype = float64)

- Aplicando el cálculo del logaritmo natural
Aplicando logaritmo al arreglo de enteros: [0.         1.38629436 2.19722458 2.77258872] (dtype = float64)
Aplicando logaritmo al arreglo de flotantes: [0.         1.38629436 2.19722458 2.77258872] (dtype = float64)
